TurnipTheBeetMKE/Controllers/GoogleMapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TurnipTheBeetMKE.Models;

namespace TurnipTheBeetMKE.Controllers
{
    public class GoogleMapsController : ApplicationBaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: GoogleMaps
        public async Task<ActionResult> Index()
        {
            return View(await db.GoogleMaps.ToListAsync());
        }

        // GET: GoogleMaps/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoogleMap googleMap = await db.GoogleMaps.FindAsync(id);
            if (googleMap == null)
            {
                return HttpNotFound();
            }
            return View(googleMap);
        }

        // GET: GoogleMaps/Create
        public ActionResult Create()
        {
            return View();
        }

        [Serializable]
        public class NameOfMarket
        {
            public string MarketName { get; set; }
        }
        [HttpPost]
        public void SaveMarketName(FarmersMarketViewModel market)
        {
            try
            {
                FarmersMarket fm = new FarmersMarket()
                {
                    marketname = market.marketname,
                    Schedule = market.Schedule,
                    Address = market.Address,
                    Products = market.Products
                };

                db.FarmersMarkets.Add(fm);
                db.SaveChanges();
            }
            catch (Exception ex)
            {

                throw;
            }
            

            RedirectToAction("Index");
        }

        // POST: GoogleMaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CurrentLocation,Destination,Name,Address,Latitude,Longitude")] GoogleMap googleMap)
        {
            if (ModelState.IsValid)
            {
                db.GoogleMaps.Add(googleMap);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(googleMap);
        }

        // GET: GoogleMaps/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoogleMap googleMap = await db.GoogleMaps.FindAsync(id);
            if (googleMap == null)
            {
                return HttpNotFound();
            }
            return View(googleMap);
        }

        // POST: GoogleMaps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CurrentLocation,Destination,Name,Address,Latitude,Longitude")] GoogleMap googleMap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(googleMap).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(googleMap);
        }

        // GET: GoogleMaps/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoogleMap googleMap = await db.GoogleMaps.FindAsync(id);
            if (googleMap == null)
            {
                return HttpNotFound();
            }
            return View(googleMap);
        }

        // POST: GoogleMaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            GoogleMap googleMap = await db.GoogleMaps.FindAsync(id);
            db.GoogleMaps.Remove(googleMap);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TurnipTheBeetMKE/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TurnipTheBeetMKE.Controllers
{
    public class HomeController : ApplicationBaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About() //MESSAGE FOR ABOUT PAGE
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() //MESSAGE FOR CONTACT PAGE
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TurnipTheBeetMKE/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title Us</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TurnipTheBeetMKE/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TurnipTheBeetMKE/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@if (User.Identity.IsAuthenticated)
{
    <div class="jumbotron">
        <h1>Started from the garden <br />now we're here</h1>
        <p class="lead">
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
            Aenean commodo ligula eget dolor.
        </p>
        <p><a href="http://localhost:4786/Home/About" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h4>Manage Your Account</h4>
            <p>Bacon ipsum dolor amet ham hock picanha beef, prosciutto capicola.</p>
            <button class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Index", "Manage")';return false;">
                Manage
            </button><br />
        </div>
        <div class="col-md-4">
            <h4>Find a farmers market</h4>
            <p>Filet mignon pancetta beef pork. Landjaeger pork andouille tongue meatloaf capicola.</p>
            <button class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Index", "GoogleMaps")';return false;">
                Locate
            </button><br />
        </div>
        <div class="col-md-4">
            <h4>News and Updates</h4>
            <p>YLorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            <p><a class="btn btn-primary btn-lg" href="#">Learn more &raquo;</a></p>
        </div>
    </div>
}
else
{
    <div class="jumbotron">
        <h1>Started from the garden <br />now we're here</h1>
        <p class="lead">
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
            Aenean commodo ligula eget dolor.

        </p>
        <p>
            <a href="http://localhost:4786/Home/About" class="btn btn-primary btn-lg">Learn more &raquo;</a>&nbsp;&nbsp;
        </p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h4>Register for a New Account</h4>
            <p>Bacon ipsum dolor amet ham hock picanha beef, prosciutto capicola.</p>
            <p><button class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Register", "Account")';return false;">
            Sign up
            </button><br /></p>
        </div>
        <div class="col-md-4">
            <h4>Find a Farmers Market</h4>
            <p>Filet mignon pancetta beef pork. Landjaeger pork andouille tongue meatloaf capicola.</p>
            <p>
                <button class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Create", "GoogleMaps")';return false;">
                    Locate
                </button><br />
            </p>
        </div>
        <div class="col-md-4">
            <h4>News and Updates</h4>
            <p>YLorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            <p><a class="btn btn-primary btn-lg" href="#">Learn more &raquo;</a></p>
        </div>
    </div>

}